[package]
name = "keyboard-aneurysm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"
inputbot = "0.5.1"
rand = "0.8.5"
